import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const dogs = [
  {
    slug: "biscuit-golden-retriever",
    name: "Biscuit",
    breed: "Golden Retriever",
    age: "2 years",
    ageCategory: "young",
    sex: "female",
    size: "large",
    weight: 55,
    color: "Golden",
    status: "available",
    fosterLocation: "Portland, OR",
    tagline: "A gentle soul who lives for belly rubs and long walks",
    bio: "Biscuit is the kind of dog who makes everyone smile. She greets every person like they're her long-lost best friend, tail wagging so hard her whole body wiggles. She was found as a stray but has adapted beautifully to home life.\n\nShe loves morning walks, playing fetch in the park, and curling up at your feet while you read. Biscuit is fully house-trained and knows basic commands — sit, stay, and an enthusiastic \"shake.\" She's looking for a family who will give her the love she so freely gives to everyone she meets.",
    personalityTraits: JSON.stringify(["Gentle", "Loyal", "Playful", "Loves Walks", "Couch Companion"]),
    energyLevel: "moderate",
    goodWithDogs: true,
    goodWithCats: true,
    goodWithKids: true,
    houseTrained: true,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: 250,
    photos: [
      { url: "https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=800&h=1000&fit=crop", alt: "Biscuit the Golden Retriever smiling", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1612774412771-005ed8e861d2?w=600&h=600&fit=crop", alt: "Biscuit playing in the park", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1625316708582-7c38734d5fd6?w=600&h=600&fit=crop", alt: "Biscuit resting on a couch", width: 600, height: 600, order: 2 },
    ],
  },
  {
    slug: "luna-pit-mix",
    name: "Luna",
    breed: "Pit Bull Terrier",
    breedSecondary: "Lab Mix",
    age: "1 year",
    ageCategory: "young",
    sex: "female",
    size: "medium",
    weight: 42,
    color: "Brindle",
    status: "available",
    fosterLocation: "Seattle, WA",
    tagline: "A wiggly lovebug with the sweetest smile in the shelter",
    bio: "Luna is pure joy wrapped in a brindle coat. She came to us from a crowded shelter down south and has been winning hearts ever since. Don't let her muscular build fool you — she thinks she's a lap dog and will try to prove it at every opportunity.\n\nLuna is incredibly smart and food-motivated, which makes training a breeze. She already knows sit, down, and is working on \"leave it\" (her biggest challenge when treats are involved). She'd thrive in an active home that can channel her enthusiasm into adventures.",
    personalityTraits: JSON.stringify(["Affectionate", "Smart", "Energetic", "Food Motivated", "Lap Dog"]),
    energyLevel: "high",
    goodWithDogs: true,
    goodWithCats: false,
    goodWithKids: true,
    houseTrained: true,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: 200,
    photos: [
      { url: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=800&h=1000&fit=crop", alt: "Luna the Pit Mix smiling", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=600&h=600&fit=crop", alt: "Luna playing with a toy", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=600&h=600&fit=crop", alt: "Luna on a walk", width: 600, height: 600, order: 2 },
    ],
  },
  {
    slug: "oakley-australian-shepherd",
    name: "Oakley",
    breed: "Australian Shepherd",
    age: "4 years",
    ageCategory: "adult",
    sex: "male",
    size: "large",
    weight: 52,
    color: "Blue Merle",
    status: "available",
    fosterLocation: "Denver, CO",
    tagline: "An adventure buddy who'll keep you on your toes",
    bio: "Oakley is a stunning blue merle Aussie with one blue eye and one brown — and a personality as striking as his looks. He's the kind of dog who needs a job to do, whether that's hiking a 14er, learning agility, or herding the neighborhood kids (gently, of course).\n\nHe spent his first years on a ranch but his previous owner could no longer care for him. Oakley is looking for an active household that understands the breed. He's incredibly loyal once bonded and will be your shadow in the best way possible.",
    personalityTraits: JSON.stringify(["Intelligent", "Athletic", "Loyal", "Driven", "Adventurous"]),
    energyLevel: "high",
    goodWithDogs: true,
    goodWithCats: null,
    goodWithKids: true,
    houseTrained: true,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: 300,
    photos: [
      { url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=1000&fit=crop", alt: "Oakley the Australian Shepherd", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=600&h=600&fit=crop", alt: "Oakley running in a field", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1477884213360-7e9d7dcc8f9b?w=600&h=600&fit=crop", alt: "Oakley portrait close-up", width: 600, height: 600, order: 2 },
    ],
  },
  {
    slug: "mochi-shiba-inu",
    name: "Mochi",
    breed: "Shiba Inu",
    age: "3 years",
    ageCategory: "adult",
    sex: "male",
    size: "small",
    weight: 22,
    color: "Red Sesame",
    status: "available",
    fosterLocation: "San Francisco, CA",
    tagline: "Independent, sassy, and impossibly photogenic",
    bio: "Mochi is a classic Shiba — dignified, a little dramatic, and absolutely convinced he's the most important being in any room. He was surrendered when his owner relocated overseas, and he's been patiently waiting for someone who appreciates his unique brand of companionship.\n\nHe's not a cuddler (he'll come to YOU when he's ready, thank you very much), but his loyalty runs deep. Mochi loves structured walks, puzzle toys, and judging you from across the room. If you want a dog with big personality in a compact package, Mochi is your guy.",
    personalityTraits: JSON.stringify(["Independent", "Sassy", "Clean", "Loyal", "Photogenic"]),
    energyLevel: "moderate",
    goodWithDogs: false,
    goodWithCats: false,
    goodWithKids: false,
    houseTrained: true,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: 350,
    photos: [
      { url: "https://images.unsplash.com/photo-1583337130417-13104dec14a3?w=800&h=1000&fit=crop", alt: "Mochi the Shiba Inu", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1600804340584-c7db2eacf0ba?w=600&h=600&fit=crop", alt: "Mochi on a walk", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=600&h=600&fit=crop", alt: "Mochi lounging", width: 600, height: 600, order: 2 },
    ],
  },
  {
    slug: "rosie-beagle",
    name: "Rosie",
    breed: "Beagle",
    age: "6 years",
    ageCategory: "adult",
    sex: "female",
    size: "medium",
    weight: 28,
    color: "Tricolor",
    status: "available",
    fosterLocation: "Austin, TX",
    tagline: "A mellow sweetheart who just wants to be near you",
    bio: "Rosie is proof that the best things in life are simple. This gentle beagle spent years as a backyard dog before being rescued, and she's been making up for lost time by soaking up every ounce of love her foster family gives her.\n\nShe's past her puppy chaos phase and has settled into the most wonderful companion dog. Rosie's favorite activities include napping in sunbeams, gentle neighborhood strolls, and following her favorite human from room to room. She's the perfect dog for someone looking for a calm, loving presence in their life.",
    personalityTraits: JSON.stringify(["Mellow", "Sweet", "Gentle", "Quiet", "Devoted"]),
    energyLevel: "low",
    goodWithDogs: true,
    goodWithCats: true,
    goodWithKids: true,
    houseTrained: true,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: 175,
    photos: [
      { url: "https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=800&h=1000&fit=crop", alt: "Rosie the Beagle", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=600&fit=crop", alt: "Rosie napping", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1587764379990-58b3413b0e16?w=600&h=600&fit=crop", alt: "Rosie in the garden", width: 600, height: 600, order: 2 },
    ],
  },
  {
    slug: "bear-bernese-mountain",
    name: "Bear",
    breed: "Bernese Mountain Dog",
    age: "5 years",
    ageCategory: "adult",
    sex: "male",
    size: "extra-large",
    weight: 95,
    color: "Tricolor",
    status: "available",
    fosterLocation: "Boulder, CO",
    tagline: "A 95-pound teddy bear who thinks he fits in your lap",
    bio: "Bear is exactly what his name suggests — a big, warm, fluffy presence that makes everything feel cozier. This majestic Bernese came from a family that loved him dearly but had to move into a small apartment. Bear needs space to stretch his magnificent fluff.\n\nDespite his size, Bear is remarkably gentle. He moves through the house like a careful giant, stepping over toys and cat tails with surprising grace. He loves cool weather, slow hikes, and leaning his full weight against your legs while you pet him. If you have room in your home and heart for a giant gentleman, Bear is ready.",
    personalityTraits: JSON.stringify(["Gentle Giant", "Calm", "Affectionate", "Patient", "Fluffy"]),
    energyLevel: "low",
    goodWithDogs: true,
    goodWithCats: true,
    goodWithKids: true,
    houseTrained: true,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: 350,
    photos: [
      { url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=1000&fit=crop&q=80", alt: "Bear the Bernese Mountain Dog", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=600&h=600&fit=crop", alt: "Bear playing in snow", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1588022274642-f238f1f51b71?w=600&h=600&fit=crop", alt: "Bear resting", width: 600, height: 600, order: 2 },
    ],
  },
  {
    slug: "pepper-border-collie",
    name: "Pepper",
    breed: "Border Collie",
    age: "8 months",
    ageCategory: "puppy",
    sex: "female",
    size: "medium",
    weight: 30,
    color: "Black & White",
    status: "available",
    fosterLocation: "Bend, OR",
    tagline: "A brilliant puppy with energy to spare and tricks to learn",
    bio: "Pepper is eight months of pure Border Collie brilliance packed into a sleek black-and-white frame. She was born on a farm but showed more interest in chasing butterflies than sheep, so she's looking for a home that can appreciate her creative spirit.\n\nShe learns new tricks in minutes (she already has a repertoire of 12), gets the zoomies at exactly 5pm every day, and has an adorable habit of tilting her head when you talk to her like she's really, truly listening. Pepper needs an experienced owner who understands that a tired Border Collie is a happy Border Collie.",
    personalityTraits: JSON.stringify(["Brilliant", "Energetic", "Quick Learner", "Playful", "Curious"]),
    energyLevel: "high",
    goodWithDogs: true,
    goodWithCats: null,
    goodWithKids: true,
    houseTrained: false,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: 300,
    photos: [
      { url: "https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=800&h=1000&fit=crop&q=80", alt: "Pepper the Border Collie puppy", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1477884213360-7e9d7dcc8f9b?w=600&h=600&fit=crop&q=80", alt: "Pepper running", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1568393691622-c7ba131d63b4?w=600&h=600&fit=crop", alt: "Pepper learning tricks", width: 600, height: 600, order: 2 },
    ],
  },
  {
    slug: "winston-french-bulldog",
    name: "Winston",
    breed: "French Bulldog",
    age: "4 years",
    ageCategory: "adult",
    sex: "male",
    size: "small",
    weight: 24,
    color: "Fawn",
    status: "pending",
    fosterLocation: "Los Angeles, CA",
    tagline: "A charming couch potato with a snore louder than his bark",
    bio: "Winston is a compact gentleman with impeccable manners and a fondness for the finer things in life — specifically, your couch, your bed, and whatever you're eating. He was surrendered when his owner's allergies became unmanageable, and he's been the star of his foster home ever since.\n\nHe's low-maintenance in the best way: a couple short walks a day, some playtime, and a warm spot to snooze and he's perfectly content. Winston does have some typical Frenchie quirks — he snores like a freight train and makes hilariously dramatic sounds when he yawns. He's currently pending adoption but we're accepting backup applications.",
    personalityTraits: JSON.stringify(["Charming", "Low-Key", "Funny", "Snuggly", "Well-Mannered"]),
    energyLevel: "low",
    goodWithDogs: true,
    goodWithCats: true,
    goodWithKids: true,
    houseTrained: true,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: 400,
    photos: [
      { url: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=1000&fit=crop&q=80", alt: "Winston the French Bulldog", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1575425186775-b8de9a427e67?w=600&h=600&fit=crop", alt: "Winston on the couch", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1585559604959-6388fe69c92a?w=600&h=600&fit=crop", alt: "Winston yawning", width: 600, height: 600, order: 2 },
    ],
  },
  {
    slug: "sage-greyhound",
    name: "Sage",
    breed: "Greyhound",
    age: "3 years",
    ageCategory: "adult",
    sex: "female",
    size: "large",
    weight: 60,
    color: "Blue Fawn",
    status: "available",
    fosterLocation: "Portland, OR",
    tagline: "A graceful retired racer who's ready for the slow life",
    bio: "Sage spent her early years on the track, but now she's discovered the joy of doing absolutely nothing at impressive speed. This elegant greyhound is the definition of \"45 mph couch potato\" — she'll sprint joyfully for about five minutes, then sleep for the next five hours.\n\nShe's adjusting beautifully to home life. Stairs were a mystery at first (they don't have those at the track), but she's mastered them with the same grace she brings to everything. Sage is quiet, gentle, and has the most soulful eyes you've ever seen. She walks beautifully on leash and is content with two moderate walks per day.",
    personalityTraits: JSON.stringify(["Graceful", "Calm", "Elegant", "Quiet", "Sweet"]),
    energyLevel: "low",
    goodWithDogs: true,
    goodWithCats: false,
    goodWithKids: true,
    houseTrained: true,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: 225,
    photos: [
      { url: "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800&h=1000&fit=crop", alt: "Sage the Greyhound", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1544568100-847a948585b9?w=600&h=600&fit=crop", alt: "Sage lounging", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=600&h=600&fit=crop", alt: "Sage on a walk", width: 600, height: 600, order: 2 },
    ],
  },
  {
    slug: "ziggy-dachshund",
    name: "Ziggy",
    breed: "Dachshund",
    age: "10 months",
    ageCategory: "puppy",
    sex: "male",
    size: "small",
    weight: 11,
    color: "Red",
    status: "available",
    fosterLocation: "Nashville, TN",
    tagline: "Tiny legs, huge personality, and a nose that never quits",
    bio: "Ziggy is ten months of dachshund determination in a long, low-rider body. He was found wandering a parking lot with no collar or chip, but his confident strut suggested he'd been on quite the adventure.\n\nThis little guy has a nose that could find a treat hidden in a vault. He's endlessly curious, surprisingly brave for his size, and has a bark that will make you laugh — it's about four sizes too big for him. Ziggy loves burrowing under blankets, chasing squeaky toys, and supervising everything from the highest spot he can reach (which admittedly isn't very high).",
    personalityTraits: JSON.stringify(["Bold", "Curious", "Funny", "Determined", "Snuggler"]),
    energyLevel: "moderate",
    goodWithDogs: true,
    goodWithCats: null,
    goodWithKids: true,
    houseTrained: false,
    spayedNeutered: true,
    vaccinated: true,
    microchipped: false,
    adoptionFee: 275,
    photos: [
      { url: "https://images.unsplash.com/photo-1612195583950-b8fd34c87093?w=800&h=1000&fit=crop", alt: "Ziggy the Dachshund", width: 800, height: 1000, order: 0 },
      { url: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=600&h=600&fit=crop", alt: "Ziggy playing", width: 600, height: 600, order: 1 },
      { url: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=600&h=600&fit=crop", alt: "Ziggy close-up", width: 600, height: 600, order: 2 },
    ],
  },
];

async function main() {
  console.log("Seeding database...");

  // Clear existing data
  await prisma.photo.deleteMany();
  await prisma.adoptionInquiry.deleteMany();
  await prisma.dog.deleteMany();

  for (const dogData of dogs) {
    const { photos, ...dog } = dogData;
    await prisma.dog.create({
      data: {
        ...dog,
        photos: {
          create: photos,
        },
      },
    });
    console.log(`  Created ${dog.name}`);
  }

  console.log(`Seeded ${dogs.length} dogs.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
